import pli from "../pli.js";
import type { libs_config } from '../libs/config.js'

const aa = pli.internalModules['configs/maxench'] = async (b) => {
    const { scoreboard, storage } = await b.import('se')
    const config = await b.importInternal('libs/config') as libs_config

    const saveId = `HX:ME:${storage.instance.default.uniqueID.slice(0, 10)}`
    const maxEnchantLevels = !scoreboard.objective.exist(saveId)
        ? Object.assign(config(scoreboard.objective.create(saveId).dummies), {
            protection: 4,
            fireProtection: 4,
            featherFalling: 4,
            blastProtection: 4,
            projectileProtection: 4,
            thorns: 3,
            respiration: 3,
            depthStrider: 3,
            aquaAffinity: 1,
            sharpness: 5,
            smite: 5,
            baneOfArthropods: 5,
            knockback: 2,
            fireAspect: 2,
            looting: 3,
            efficiency: 5,
            silkTouch: 1,
            unbreaking: 3,
            fortune: 3,
            power: 5,
            punch: 2,
            flame: 1,
            infinity: 1,
            luckOfTheSea: 3,
            lure: 3,
            frostWalker: 2,
            mending: 1,
            binding: 1,
            vanishing: 1,
            impaling: 5,
            riptide: 3,
            loyalty: 3,
            channeling: 1,
            multishot: 1,
            piercing: 4,
            quickCharge: 3,
            soulSpeed: 3,
            swiftSneak: 3,
        })
        : config(scoreboard.objective.edit(saveId).dummies)
    
    const compatibleEnchantments = (list: string[] = []): Record<string, number> => {
        const o = Object.create(null)
        for (const k of list) Object.defineProperty(o, k, { get: () => maxEnchantLevels[k], set: (v) => maxEnchantLevels[k] = v })
        return o
    }
    const slotCompatibleEnchantments: Record<number, Record<string, number>> = Object.setPrototypeOf({
        0: compatibleEnchantments(),
        1: compatibleEnchantments([
            'protection',
            'fireProtection',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'respiration',
            'aquaAffinity',
            'unbreaking',
            'mending',
            'binding',
            'vanishing'
        ]),
        2: compatibleEnchantments([
            'protection',
            'fireProtection',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'unbreaking',
            'mending',
            'binding',
            'vanishing',
        ]),
        4: compatibleEnchantments([
            'protection',
            'fireProtection',
            'featherFalling',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'depthStrider',
            'unbreaking',
            'frostWalker',
            'mending',
            'binding',
            'vanishing',
            'soulSpeed',
        ]),
        8: compatibleEnchantments([
            'protection',
            'fireProtection',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'unbreaking',
            'mending',
            'binding',
            'vanishing',
            'swiftSneak',
        ]),
        15: compatibleEnchantments([
            'protection',
            'fireProtection',
            'featherFalling',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'respiration',
            'depthStrider',
            'aquaAffinity',
            'unbreaking',
            'frostWalker',
            'mending',
            'binding',
            'vanishing',
            'soulSpeed',
        ]),
        16: compatibleEnchantments([
            'sharpness',
            'smite',
            'baneOfArthropods',
            'knockback',
            'fireAspect',
            'looting',
            'unbreaking',
            'mending',
            'vanishing',
        ]),
        32: compatibleEnchantments([
            'unbreaking',
            'power',
            'punch',
            'flame',
            'infinity',
            'mending',
            'vanishing',
        ]),
        64: compatibleEnchantments([
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        128: compatibleEnchantments([
            'efficiency',
            'silkTouch',
            'unbreaking',
            'mending',
            'vanishing',
        ]),
        256: compatibleEnchantments([
            'unbreaking',
            'mending',
            'vanishing',
        ]),
        512: compatibleEnchantments([
            'sharpness',
            'smite',
            'baneOfArthropods',
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        1024: compatibleEnchantments([
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        2048: compatibleEnchantments([
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        3648: compatibleEnchantments([
            'sharpness',
            'smite',
            'baneOfArthropods',
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        4096: compatibleEnchantments([ 
            'unbreaking',
            'luckOfTheSea',
            'lure',
            'mending',
            'vanishing',
        ]),
        8192: compatibleEnchantments([ 
            'unbreaking',
            'mending',
            'vanishing',
        ]),
        16384: compatibleEnchantments([ 
            'unbreaking',
            'mending',
            'binding',
            'vanishing',
        ]),
        32768: compatibleEnchantments([
            'unbreaking',
            'mending',
            'vanishing',
            'impaling',
            'riptide',
            'loyalty',
            'channeling',
        ]),
        65536: compatibleEnchantments([
            'unbreaking',
            'mending',
            'vanishing',
            'multishot',
            'piercing',
            'quickCharge',
        ]),
        131072: compatibleEnchantments([
            'unbreaking',
            'mending',
            'vanishing',
        ]),
        131520: compatibleEnchantments([
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'mending',
            'vanishing',
        ]),
        262144: compatibleEnchantments([
            'binding',
            'vanishing',
        ]),
        524288: compatibleEnchantments([
            'binding',
            'vanishing',
        ]),
        1048576: compatibleEnchantments([
            'binding',
            'vanishing',
        ]),
        '-1': compatibleEnchantments([
            'protection',
            'fireProtection',
            'featherFalling',
            'blastProtection',
            'projectileProtection',
            'thorns',
            'respiration',
            'depthStrider',
            'aquaAffinity',
            'sharpness',
            'smite',
            'baneOfArthropods',
            'knockback',
            'fireAspect',
            'looting',
            'efficiency',
            'silkTouch',
            'unbreaking',
            'fortune',
            'power',
            'punch',
            'flame',
            'infinity',
            'luckOfTheSea',
            'lure',
            'frostWalker',
            'mending',
            'binding',
            'vanishing',
            'impaling',
            'riptide',
            'loyalty',
            'channeling',
            'multishot',
            'piercing',
            'quickCharge',
            'soulSpeed',
            'swiftSneak'
        ])
    }, null)
    
    return {
        maxEnchantLevels,
        slotCompatibleEnchantments
    }
}

export type config_maxench = ReturnType<typeof aa>
